### ISSUE TITLE
How to detect / activate 'edit mode' in the Order edit app

### ISSUE THREAD

**Issue by michaelrog** [craftcms/commerce#1904]
We have a plugin adding some ad-hoc fields to the Order Edit form using the `cp.commerce.order.edit.main-pane` hook. (These are form fields added directly by the plugin, not Custom Fields, processed as part of a normal Order-edit form submission.)

I need a way to trigger Commerce's Vue app to go into 'edit mode' (as though the user clicked the "Edit" button) when these fields are updated, so that the "Update Order" button will be accessible and the user can save the form.

Alternatively, I need a way to Subscribe to the Vue app's state, so that I can disable the form fields by default, and only make them editable if the Vue app is in "edit mode."

Adding controls to the Order Edit screen seems to be a common need — c.f. #138, #865, #1742, and especially #1269 — but rather than trying to inject content into the Vue app, I just need to know how to get at whatever state controls the "edit mode" i.e. the state of the "Update Order" form submit button.

Could yall provide some guidance on this?

**Comment by lukeholder** [comment]
We need to allow you to add tabs. Working on this now.

You could then add both a static version (uneditable) of your fields in one tab, and the editable in another. Then the javascript we have on the page should show and hide the static tabs depending on if you are in edit mode. See:

https://github.com/craftcms/commerce/blob/develop/src/web/assets/commerceui/src/js/order/apps/OrderActions.vue#L66-L89

Your customer tabs should have the `custom-tab` class, and the static one should have the `static` class.

I am adding a `cp.commerce.order.content` hook to the page now (https://github.com/craftcms/commerce/issues/1269), so you can add tab content divs to the page the same way we do for transactions and order history. Your static tab div ID would be the same as the non static one, but prepended with `#static-`

The `cp.commerce.order.edit.main-pane` hook only added content to the bottom of the order details tab, so using the new hook above is better.

Working on this, so keep an eye on this ticket.

**Comment by lukeholder** [comment]
This has been fixed for the next release:

You will then be able to do the following:

```
        Event::on(OrdersController::class, OrdersController::EVENT_REGISTER_ORDER_TABS,
            function(OrderTabsEvent $event) {
                $tabs = $event->tabs;
                $tabs[] = [
                    'label' => Craft::t('commerce', 'Mine'),
                    'url' => '#mineTab',
                    'class' => 'custom-tab'
                ];
                $tabs[] = [
                    'label' => Craft::t('commerce', 'Mine'),
                    'url' => '#static-mineTab',
                    'class' => 'custom-tab static'
                ];
                $event->tabs = $tabs;
            }
        );
```
with the new `cp.commerce.order.content` hook you would add:

<div id="mineTab">MINE</div>
<div id="static-mineTab">READ ONLY STATIC MINE</div>

**Comment by michaelrog** [comment]
Thank you @lukeholder! — It looks like this works for adding and navigating the tabs.

However, when a user changes a value in the custom tab fields, the "Update Order" button does not become enabled, so it's still not possible for the user to actually save the changes. (This appears to be the case for Craft custom fields as well.) 

Is there some JS we need to be calling to tell Commerce/Vue that there are changes to be saved?

**Comment by michaelrog** [comment]
> It's likely you haven't added a customer? With a customer the update button is available. It's A requirement of updating/saving an order.

Ah, I had a saved Customer, but no line items. Adding line items did cause the Update Order button to be enabled.

**Comment by michaelrog** [comment]
> and you will also be able to also use the static variable in those templates.

More info (or docs) about this would be helpful... Are you referring to a variable in JS that represents the "edit mode" state?

> He instead recommends using the field layout to add tabs and inline templates for forms ... Would that work too?

With that approach, a plugin would have no first-party way to add its own tab to the Order edit screen. To make that user-friendly for a plugin user, we'd have to create a custom Fieldtype... which requires an admin to go through the extra steps of creating a form (and using Twig)... and then, presumably, we'd run into issues where the forms in question could be added to a Field Layout more than once, and other related anomalies... To me, that doesn't sound like a better situation.

**Comment by lukeholder** [comment]
@michaelrog we are discussing your points internally at the moment. Will let you know what we decide soon.

**Comment by lukeholder** [comment]
> Ah, I had a saved Customer, but no line items. Adding line items did cause the Update Order button to be enabled.

We removed the requirement for line items in the next release so only customer will be required.

**Comment by lukeholder** [comment]
@michaelrog Brandon has asked that you submit a feature request on craftcms/cms repo to be able to add tabs at runtime to field layouts.

I am reverting my order specific tab event before cutting the next release.

**Comment by michaelrog** [comment]
Makes sense.

I was actually able to accomplish everything I need by hijacking the Twig context in the `cp.commerce.order.edit` hook. The missing piece was your [comment](https://github.com/craftcms/commerce/issues/1904#issuecomment-737066070) explaining the Commerce/Vue convention for rendering static/dynamic fields.

We'll poke a FR into the `cms` repo re: adding tabs at runtime... fwiw, I suspect you'll still want to document the static/dynamic field setup you use in Commerce, since anybody adding tabs at runtime will need to imitate your convention.

Thanks! 🍻
