### ISSUE TITLE
Product Fixture is broken on Craft 3.6

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#2003]
**Description**
When running Craft 3.6 with Commerce's ProductFixture, I see the following error:

```
Exception 'Error' with message 'Class 'craft\test\fixtures\elements\ElementFixture' not found'
in /app/user/vendor/craftcms/commerce/src/test/fixtures/elements/ProductFixture.php:25
```

**To Reproduce**
How, and what happened?
1. Install Craft 3.6
2. Use the ProductFixture

**Expected behavior**
It should work

**Additional info**
- Craft version: 3.6.5.1
- Commerce version: 3.2.14.1
- PHP version: 7.4.15
- Database driver & version: PostgreSQL 12.5
- Other Plugins & versions: -

**Additional context**
cc @brandonkelly

**Comment by lukeholder** [comment]
Hi @boboldehampsink, we have a 3.3 Commerce release due out soon that is a Craft 3.6 compatibility release. It includes updates to our tests, working correctly with the Craft 3.6 test changes. Stay tuned!

**Comment by nfourtythree** [comment]
Hi

We have pushed further updates to the `3.3` branch that should see everything brought up to speed/compatibility with Craft `3.6`.

Thanks.

**Comment by boboldehampsink** [comment]
hi @nfourtythree @lukeholder, any ETA on 3.3?

**Comment by lukeholder** [comment]
@boboldehampsink next week or so.

**Comment by boboldehampsink** [comment]
Come on guys, it has been 3 months since Craft 3.6 has been released and I still can't update my Commerce sites because I need 3.3

**Comment by boboldehampsink** [comment]
Another month guys

**Comment by nfourtythree** [comment]
Hey @boboldehampsink 

3.3 was released with these updates ~10 days ago. https://github.com/craftcms/commerce/releases/tag/3.3.0

You should be good for updating now.

Thanks!

**Comment by boboldehampsink** [comment]
@nfourtythree thanks!
