### ISSUE TITLE
Gateway setting overrides in 3.3 do not work from plugin config file.

### ISSUE THREAD

**Issue by lukeholder** [craftcms/commerce#2101]
**Description**

commerce-gateways.php (DEPRECATED)
```php
return [
    'paypal' => [
        'testMode' => getenv('PAYPAL_TEST_MODE'),
    ]
];
```

commerce-paypal-checkout.php
```php
return [
    'testMode' => getenv('PAYPAL_TEST_MODE'),
];
```

With commerce-gateways.php the "Test Mode" lightswitch in the panel change based on my ENV variable, but with the new file (commerce-paypal-checkout.php) it doesn't.

I have added die('test') in commerce-paypal-checkout.php and the application was stopped, so the file name is correct.

**Comment by nfourtythree** [comment]
For anyone running into this, although the `commerce-gateways.php` override method has been deprecated it still works and can continue to be used, [see documentation](https://craftcms.com/docs/commerce/3.x/gateway-config.html).

If you would like to avoid the deprecation errors you can override the settings in a module by using dependency injection:

```php
Craft::$container->set(\craft\commerce\paypalcheckout\gateways\Gateway::class, function($container, $params, $config) {
    $handle = 'myPayPalGateway';
    // Return the current settings if it is a new instance or the not the handle of the gateway we want to change
    if (empty($config['id']) || $config['handle'] != $handle) {
        return new \craft\commerce\paypalcheckout\gateways\Gateway($config);
    }

    return new \craft\commerce\paypalcheckout\gateways\Gateway(array_merge($config, ['testMode' => getenv('MY_TEST_MODE')]));
});
```

We are still investigating and discussing internally what will be the new method for overrides, paying close attention to how environment variables work with lightswitch fields.

**Comment by mattstein** [comment]
This is for anyone trying and fix the deprecation error:

> Overriding gateway settings using the commerce-gateways.php file has been deprecated. Use the gateway’s config file instead.

You _can_ use a standard plugin config file named `[plugin-handle].php` and return an array with the settings you’d like to override. If you’ve used your gateway plugin to establish a single gateway, you’re good to go—just be careful if you’re trying to set the gateway’s `testMode` or any boolean value [with an environment variable](https://github.com/craftcms/cms/issues/6403).

A Commerce gateway plugin may establish multiple gateway instances, however, which the deprecated `commerce-gateways.php` accounted for with a top-level key for each gateway instance. There’s no equivalent convention in a standard config file like the `commerce-paypal-checkout.php` example above, hence my comment here and the open issue.

The way to deal with the deprecation error is to either:

1. Ignore it for now, since the team’s aware of the problem and your gateway will continue to work.
2. Use dependency injection as @nfourtythree suggests, accounting for your different gateway handles and any other settings you might want to customize.

**Comment by lukeholder** [comment]
All gateway in 4.0 support environment variables for every setting, so this is solved. 4.0  RC out soon.

**Comment by bossanova808** [comment]
I've just tried this as part of my _very slow_ progress towards C4C4...

I have a `commerce-e-way-rapid.php` file in my config, and in that is:

```php
<?php
// We use env vars here...only the .env.production has the live values, the rest use sandbox values...
use craft\helpers\App;

return [
        'testMode' => App::parseEnv('GATEWAY_TESTMODE'),
        'apiKey' => getenv('EWAY_API_KEY'),
        'password' => getenv('EWAY_PASSWORD'),
        'CSEKey' => getenv('EWAY_CSE_KEY'),
        'sendCartInfo' => false,
];
```

...however, I have the same issue as above - when I load the settings page for this Gateway, test mode hows 'off' rather than on - exactly the same behaviour I see as with C3C3...

In the .env file I have tried both `true` and `1` as the values, and I have tried simply `getenv` and `App::parseEnv` as above.

Any hints as to what I am doing wrong, since from the above, this should work, it seems?

**Comment by bossanova808** [comment]
Have also tried `commerce-eway.php` which I suspect is right...be good if the names were documented at:
https://craftcms.com/docs/commerce/4.x/payment-gateways.html#storing-config-outside-of-the-database (@mattstein)

But the settings are still not being picked up... help would be appreciated!

**Comment by sjelfull** [comment]
@nfourtythree But I don't see how we can do it for boolean values not using a string input?
