### ISSUE TITLE
[4.x]: Cannot set `firstName` and `lastName` via Cart

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#3015]
### What happened?

Followed my own ding-dang-docs and found an error. Thanks to Rob on Discord for pointing it out! I've altered the example to avoid further confusion, but still believe we've found a behavioral issue in Commerce.

### Description

_Tracking internally, but filing so we can point at it publicly!_

Currently, it is not possible to set `firstName` and `lastName` discretely via `shippingAddress` and `billingAddress` (using `commerce/cart/update-cart`).

I believe this is due to the difference in handling POST data between this action and `user/save-address`, which calls [`UserController::populateNameAttributes($model)`](https://github.com/craftcms/cms/blob/develop/src/controllers/UsersController.php#L2523) to reconcile first/last/full params.

### Steps to reproduce

```twig
{# templates/address-update.twig #}

{% set flashes = craft.app.session.getAllFlashes() %}

{% if flashes | length %}
    <ul>
        {% for key, flash in flashes %}
            <li>{{ flash }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% set cart = craft.commerce.carts.cart %}
{% set shippingAddress = cart.shippingAddress %}

{{ dump(cart.getErrors()) }}

<form method="post">
    {{ csrfInput() }}
    {{ actionInput('commerce/cart/update-cart') }}

    {{ input('text', 'shippingAddress[addressLine1]', shippingAddress.addressLine1 ?? null) }}
    {{ input('text', 'shippingAddress[locality]', shippingAddress.locality ?? null) }}
    {{ input('text', 'shippingAddress[administrativeArea]', shippingAddress.administrativeArea ?? null) }}
    {{ input('text', 'shippingAddress[countryCode]', shippingAddress.countryCode ?? null) }}
    {{ input('text', 'shippingAddress[postalCode]', shippingAddress.postalCode ?? null) }}
    {{ input('text', 'shippingAddress[firstName]', shippingAddress.firstName ?? null) }}
    {{ input('text', 'shippingAddress[lastName]', shippingAddress.lastName ?? null) }}

    <button>Set Name</button>
</form>
```

### Expected behavior

`firstName` and `lastName` are set and rendered back into the form upon saving, matching the functionality of `users/save-address`.

### Actual behavior

Neither value is set. `fullName` is still honored.

### Craft CMS version

4.0.0+

### Craft Commerce version

4.0.0+

### PHP version

8.0.24

### Operating system and version

Docker/Alpine

### Database type and version

MySQL

### Installed plugins and versions

-

**Comment by AugustMiller** [comment]
Aye—we have been discussing this internally.

In the interim, I made a sneaky change to the docs in hopes of steering others away from the discrepancy! 😜

**Comment by pdaleramirez** [comment]
This is not a bug. On Commerce 4 addresses are handled by the CMS. Use the Address Element to save firstName and lastName to the address object.

**Comment by lenvanessen** [comment]
@pdaleramirez  what do you mean by use the Address Element? We've come across this as well, many Commerce 3 stores use firstName and lastName as separate fields. How do we include them? As fields? Because the columns are still there in the address, so i'm not sure why the logic would be missing to process them.

**Comment by pdaleramirez** [comment]
@lenvanessen I would suggest to review this Craft CMS 4 Address documentation: https://craftcms.com/docs/4.x/addresses.html

You can actually set firstName and lastName, you can follow this example templates here: https://github.com/craftcms/commerce/blob/develop/example-templates/dist/shop/_private/address/fields.twig

Then test by adding this firstName and lastName html input

```
    <label for="firstName">
      {{- 'First Name'|t -}}
    </label>
    {{ input('text', 'firstName', address.firstName ?? '', {
      id: 'firstName',
      class: ['w-full', 'border border-gray-300 hover:border-gray-500 px-4 py-2 leading-tight rounded']
    }) }}
    {{ _self.displayErrors(address, 'firstName') }}
  </div>

  <div class="my-2">
    <label for="lastName">
      {{- 'Last Name'|t -}}
    </label>
    {{ input('text', 'lastName', address.lastName ?? '', {
      id: 'lastName',
      class: ['w-full', 'border border-gray-300 hover:border-gray-500 px-4 py-2 leading-tight rounded']
    }) }}
    {{ _self.displayErrors(address, 'lastName') }}
  </div>
```

**Comment by lenvanessen** [comment]
@pdaleramirez  it doesn't save through the update cart method?

**Comment by pdaleramirez** [comment]
@lenvanessen You can follow the example template here: https://craftcms.com/docs/commerce/4.x/addresses.html#cart-address-examples

**Comment by WHITE-developer** [comment]
@pdaleramirez https://github.com/craftcms/commerce/issues/3015#issuecomment-1378735596 This works fine on the `users/save-address` controller, but on the `commerce/cart/update-cart` controller the values aren't set correctly, using fullName works fine, but it's giving problems when external system's like gateways that are requiring a last name, with just the fullName field there is not really a way to force people to fill in there last name, and if they only fill in 1 name, it's getting picked up as first name

**Comment by pdaleramirez** [comment]
> @pdaleramirez [#3015 (comment)](https://github.com/craftcms/commerce/issues/3015#issuecomment-1378735596) This works fine on the `users/save-address` controller, but on the `commerce/cart/update-cart` controller the values aren't set correctly, using fullName works fine, but it's giving problems when external system's like gateways that are requiring a last name, with just the fullName field there is not really a way to force people to fill in there last name, and if they only fill in 1 name, it's getting picked up as first name
@WHITE-developer good point, I'll re-open this issue and mark it as enhancement.

**Comment by bossanova808** [comment]
This is another example of a an obvious, basic functionality bug, that needs urgent fixing.  It's been open since October last year?? That's - crazy.  

Just about every e-commerce gateway / anti-fraud system needs a first and last name.  And anyone (like me) updating from a Craft 3 / Commerce 3 system is going to hit this with their checkout and be absolutely baffled why it isn't working, and the only way to work out it is broken is to see August talking about it in Discord and/or find this bug report.

You folks really need to life your game with Commerce, it's feeling thoroughly neglected to your long time users.

**Comment by lukeholder** [comment]
This is fixed for the next release. You can now set `firstName` and `lastName` on addresses on the cart when you omit submitting a `fullName`.

Will let you know when it is out.

**Comment by joshuapease** [comment]
Hi @lukeholder! Any word on when this will be released? 

I'm currently in the middle of a Craft 3 -> 4 migration and got bitten by this issue.

**Comment by philipboomy** [comment]
> This is another example of a an obvious, basic functionality bug, that needs urgent fixing. It's been open since October last year?? That's - crazy.
> 
> Just about every e-commerce gateway / anti-fraud system needs a first and last name. And anyone (like me) updating from a Craft 3 / Commerce 3 system is going to hit this with their checkout and be absolutely baffled why it isn't working, and the only way to work out it is broken is to see August talking about it in Discord and/or find this bug report.
> 
> You folks really need to lift your game with Commerce, it's feeling thoroughly neglected to your long time users.

I agree completely. These weird changes makes no sense to me. Why remove first name and last name?
Luke has been very kind to me on several occasions so nothing against him at all but the Commerce team was pulled away from Commerce to work on Cloud (I think) and then Commerce is put on the back burner. Still waiting for Apple Pay. Every other eCommerce system supports it. My clients are wondering what's happening. They are amazed about how flexible the system is but then frustrated about the issues.

**Comment by joshuapease** [comment]
Looks like this is out in `4.3.0`. 

Thanks you for the release 🙏

**Comment by hatyi** [comment]
Hello everyone!

Are you absolutely sure that this is working as intended?
I'm also struggling with the firstName lastName address fields for shipping and billing addresses while using the `actions/commerce/cart/update-cart` action.

I'm not sending fullName as suggested, was just wondering if I'm doing something wrong or this functionality is unfortunately still broken.

I'm using 4.4.17 CMS version and 4.2.7 Commerce.

Thanks in advance!

**Comment by philipboomy** [comment]
How would we go about making firstName and lastName required? I tried adding firstName and lastName to the address fields https://share.zight.com/7KuXbzrk but that its giving validation error on actions/commerce/cart/update-cart

**Comment by AugustMiller** [comment]
@philipboomy It looks like you've re-implemented the `firstName` and `lastName` attributes as custom fields?

Ultimately, I don't think this has to do with Commerce—in order to use your custom fields, you would have to send `fields[firstName]` and `fields[lastName]` values in a POST request to `users/save-address`, or `shippingAddress[fields][firstName]` and `shippingAddress[fields][lastName]` to `commerce/cart/update-cart`. (`billingAddress` would also work for the Commerce action!)

**Comment by philipboomy** [comment]
Thanks for responding.

Yeah I added firstName and lastName as an attempt to force validation but as you are rightfully saying is that they are then treated as custom fields. I am just trying to use firstName and lastName as implemented in latest update of Commerce but only fullName seems native and thereby the only name field that can be validated.

**Comment by lukas-jansen** [comment]
```
Event::on( Address::class, Model::EVENT_DEFINE_RULES, static function(DefineRulesEvent $event): void { if (Craft::$app->getRequest()->getIsSiteRequest()) { $event->rules[] = [ [ 'firstName', 'lastName', ], 'required', ]; } }, ); 
```
This will make both required

**Comment by hatyi** [comment]
I think it's slightly confusing about the order addresses that the name fields are only rendered if they are set on either of the address attached to the order, talking about the CP view `/admin/commerce/orders/orderId`, and if you click on the attached address (bringing up the slide in editor), you can not see them as inputs - even if they have values. 
So initially you might be "tricked" into thinking you have to add them manually to the Address field layout.

Surely the fact that we couldn't set them through the `commerce/cart/update-cart` action wasn't helping😅, but thankfully that's resolved now. Still I think this part is not really intuitive.

**Comment by philipboomy** [comment]
Yeah I appreciate the quick help from the team. Even providing full code example. So please don't take this as negative but more like my opinion. It was confusing to me too and will most likely be confusing to others that full name shows up in the slide out and can be set as required but first name and last name can't. Yet we can set those values in the update cart controller without them being custom fields. I understand that the first name and last name was added back in as it would requested and we apporeciate that but they are right now floating between being native (built in) and custom fields.

**Comment by terryupton** [comment]
Anyone who has come across this issue. How did you handle the validation for existing addresses?
I am getting the following error if I try and select an existing address (it has a full name in the back-end) but this is now showing on the front-end. If I select the address in the checkout process I see this error.

<img width="1972" alt="Screenshot 2024-08-28 at 11 09 49" src="https://github.com/user-attachments/assets/48d3e31d-2fcc-4bf3-97c5-4051d3c41191">
<img width="1602" alt="Screenshot 2024-08-28 at 11 23 23" src="https://github.com/user-attachments/assets/501c7f8a-1ce8-4206-b991-6ea9a34f66f0">
815-d39f3b943985">
<img width="1235" alt="Screenshot 2024-08-28 at 11 27 22" src="https://github.com/user-attachments/assets/f92c644f-0ae2-4585-b097-cbfa6987b531">
<img width="1581" alt="Screenshot 2024-08-28 at 11 27 29" src="https://github.com/user-attachments/assets/b72d42d5-1707-4ab8-b854-024ef1d6f2ef">
<img width="646" alt="Screenshot 2024-08-28 at 11 40 52" src="https://github.com/user-attachments/assets/49c91963-f026-462b-9c73-5ebc5cdb0b19">

Hoping someone has a solution for this. 
I have 2 commerce sites to upgrade and both will need this solution.
