### ISSUE TITLE
[5.x]: Pricing rules purchasable rule not working for multi store

### ISSUE THREAD

**Issue by white-lukas** [craftcms/commerce#3917]
### Description
Site/store setup
Site A -> Store A
Site B -> Store B

1 product type where propagation method is set to `Save product to other sites in the same site group` (sites are in different groups)

When trying to create a pricing rule for Store B the purchasable selector only shows products from Site A.

The same happens when trying to create a pricing rule from the variant directly,
the purchasable condition stays empty.

When I change the `site` parameter in the url which is by default still the site handle from Site A while browsing the store settings from Store B, I do see the products from Site B. but after saving the pricing rule the purchasable condition is back empty

The same happens when creating a pricing rule by code
eg.
```PHP
if ($this->storeHandle !== null) {
            $store = Plugin::getInstance()->getStores()->getStoreByHandle($this->storeHandle);
        }

        $store = $store ?? Plugin::getInstance()->getStores()->getPrimaryStore();

        /** @var CatalogPricingRule $catalogPricingRule */
        $catalogPricingRule = Craft::createObject([
            'class' => CatalogPricingRule::class,
            'storeId' => $store->id,
        ]);

        $catalogPricingRule->name = $catalogPricingRuleIdentity;
        $catalogPricingRule->isPromotionalPrice = $this->catalogPricingIsPromotional;

        $rule = Craft::$app->getConditions()->createConditionRule([
            'class' => PurchasableConditionRule::class,
            'elementIds' => [Variant::class => [$variant->getId()]],
        ]);

        /** @var CatalogPricingRulePurchasableCondition $purchasableCondition */
        $purchasableCondition = Craft::$app->getConditions()->createCondition(CatalogPricingRulePurchasableCondition::class);
        $purchasableCondition->addConditionRule($rule);
        $catalogPricingRule->setPurchasableCondition($purchasableCondition);

        return $catalogPricingRule;
```

Might be related/the same as https://github.com/craftcms/commerce/pull/3903?

### Craft CMS version

5.6.9.1

### Craft Commerce version

5.3.3

### PHP version

8..3.12

**Comment by nfourtythree** [comment]
Hi @white-lukas 

Thank you for bringing this to our attention. We have pushed a fix which will be included in the next release of Commerce.

This fix enables the site selector for condition rules dealing with selecting elements. This should give the ability to select the element from the correct site.

After this, we are also going to review the UI/UX regarding sites and element selection when it comes to settings and features related to a store.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.3.4",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by white-lukas** [comment]
Hi @nfourtythree,
The selection is working now, but it looks like the prices are not getting applied.

On the Variant page, the `Show all prices` is not showing the catalog pricing rules and only shows the message `Pricing jobs are currently running` while their are no queue jobs running, and even when generating the catalog prices with the console command, they don't show up and the message that the jobs are currently running is still there.

On the primary site, they do work, but the message is also shown their

**Comment by nfourtythree** [comment]
Hi @white-lukas 

Thank you for your response, we have pushed up another fix which we believe will help with this.

If you could try it and let us know how it goes that would be a great help.

To get this fix, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.3.5",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Hi All

A further fix for this has been pushed to the `5.x` branch and will be included in the next release of Commerce.

To get this early, change your `craftcms/commerce` requirement in your project's `composer.json` to:

```json
"require": {
  "craftcms/commerce": "5.x-dev as 5.3.5",
  "...": "..."
}
```

Then run `composer update`.

Thanks!

**Comment by nfourtythree** [comment]
Commerce 5.3.6 has been released with this fix included.

Thanks!

**Comment by wanze** [comment]
Hi

After updating to Commerce `5.3.6` I still have the issue that the pricing rules for non-primary stores are not applied on variants.

**How to reproduce**

* Create a secondary store
* Create a new product with some variants in the secondary store
* Create a new pricing rule for the secondary store
  * e.g. 10% off everything, only targeting the product type with a 10% reduction as promotional price

![Image](https://github.com/user-attachments/assets/d19038af-b6f1-4fcc-846f-08b19c3b025f)

Then, after the `CatalogPricing` job has finished, open a variant in the secondary store. There are no pricing rules applied. Works fine if I configure the same rule for the primary store.

![Image](https://github.com/user-attachments/assets/ba66de9e-9a71-400e-a238-232d51d8e9aa)
